### ISSUE TITLE
Converting the metadata corners to draw an overlay.

### ISSUE THREAD

**Issue by acf** [MattFoley/Smerk#3]
Hi Matt, 

Not an issue so much as a feature (or just opinion) request.  I started using GPUImage (not Smerk) to read barcodes so I could take advantage of blur filtering the camera.  The blocker I hit is that in the apple sample code the corners of the metadata objects need translated from a (0..1) range into points of the camera preview window.

In the apple code this is done using AVCaptureVideoPreviewLayer transformedMetadataObjectForMetadataObject: or rectForMetadataOutputRectOfInterest: (  https://developer.apple.com/library/ios/Documentation/AVFoundation/Reference/AVCaptureVideoPreviewLayer_Class/Reference/Reference.html#//apple_ref/occ/instm/AVCaptureVideoPreviewLayer/transformedMetadataObjectForMetadataObject: )

Using GPUImage for the camera view exposes no such layer.

I happened upon Smerk and hoped it would solve my problem, but it appears it does as much as I've already pieced together myself - returning the basic metadata objects - albeit in a much cleaner way :-)

I've tried the maths myself a couple of times - I figured it would be as simple as metadatapoint.x \* camera view.bounds.size.x etc but that hasn't worked.

Any ideas on how Smerk could add this so that the exposed barcode and face objects could be highlighted on the camera view ?

Thanks in advance for your thoughts,

Alan

**Comment by MattFoley** [comment]
This is a good question. Off the top of my head, no I don't have a good idea for how to do this, although I will think about it and get back to you.

**Comment by MattFoley** [comment]
Sorry that I've never gotten back to you, 2 months later. I think for now I'm not going to attempt to implement this in this library. There's just far too much customization that would be happening per use of this project. I'll leave this open though, just in case I have a better idea and some free time.

**Comment by MattFoley** [comment]
A nice guy just implemented this into the library, so if you're still looking for this, it's now here.

**Comment by acf** [comment]
Just spotted this reply Matt.  Thanks!  Looks like the switch statement on the camera fill mode is the trick I was missing :-)
