### ISSUE TITLE
Don't know how to use it

### ISSUE THREAD

**Issue by bagusflyer** [MattFoley/Smerk#4]
How to use it? I run the app, camera is on. But that's all. It does nothing other than that. What should I do?

**Comment by MattFoley** [comment]
Smerk doesn't give you a UI implementation, as that's very specific to your implementation.

If you check the header files, readme and your output logs, you'll see that the example app can detect a range of items for you, faces mainly, both 3D information and 2D as well as many machine readable codes, such as barcodes, QR codes etc. Smerk can do all of that for you and help manage your interface with the camera. Then it's up to you to decide how to use that information. 

If you have any specific questions, I'd be happy to help.

**Comment by bagusflyer** [comment]
Thanks, I thought the demo will show something.
